### ISSUE TITLE
Find issues to resolve for this lesson

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-git#1]
This lesson has now been migrated to the Library Carpentry organisation. Work should happen on THIS repo.

All the issues that need resolving are still at the old location, however: https://github.com/data-lessons/library-git-DEPRECATED/issues

Find issues to resolve *there* and fix them **here**.

**Comment by dcmcand** [comment]
Since there are no more issues open in the old repo, can we close this issue now?
