### ISSUE TITLE
Address changing authentication requirements in Lesson 3

### ISSUE THREAD

**Issue by kevintfrench** [LibraryCarpentry/lc-git#100]
GitHub is changing requirements for command line interaction on August 13, 2021.   While practicing for an upcoming workshop, I found using the instructions under Pushing Changes in Lesson 3 prompted am email Deprecation Notice email from GitHub which may disrupt the flow of a lesson.  I recommend addressing the new requirements outlined here https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by dcmcand** [comment]
Hi @kevintfrench,
Pull requests are welcome if you have time to put something together.

**Comment by ha0ye** [comment]
We are already seeing this as an issue in https://ha0ye.github.io/2021-06-15-uthsc-online/ -- we ended up using ssh-keys and demoing it (since the ssh-key bits can be screen-shared without concern for sharing a private key or PAT)

**Comment by emcaulay** [comment]
I would like to help in revising this lesson to address the issue. I looked through the lesson, and I'd like to make sure I understand where to make the changes. 

If I understand correctly, we should revise the setup portion of the lesson to include SSH key setup. So that when we get to Episode 3 of the Lesson we are not stopped by the interruption of the "Deprecation Notice" from Github.

**Comment by ha0ye** [comment]
@emcaulay Yup, that seems like the spot for me. This change will also help future-proof the lesson, since the existing method will require an update when Github implements its changes on August 13 anyway.

**Comment by kevintfrench** [comment]
Yes, that is the location and issue.  Any help would be appreciated.  At our last workshop, we ended up having the participants contact me to do this along with the other prerequisites.

**Comment by emcaulay** [comment]
Just an update to everyone here about this issue. I spoke with @tobyhodges yesterday (July 1, 2021), and our approach is to make sure that we align the library carpentry lesson with the software carpentry lesson on this issue of github authentication. There is substantial discussion taking place in the software carpentry lesson issue here: https://github.com/swcarpentry/git-novice/issues/778

**Comment by PhilReedData** [comment]
I have just learned that SWC has merged its SSH changes into their Git lesson now, see the ['Remotes' episode](http://swcarpentry.github.io/git-novice/07-github/index.html) and [recent commits](https://github.com/swcarpentry/git-novice/commits/gh-pages).

**Comment by emcaulay** [comment]
Hi @PhilReedData , I collaborated with @kekoziar to plan and then review the updates to the SWC lesson. I am now working on updating the LC lesson to also use SSH. 

My plan is to complete this by the end of day Pacific Time on Friday, July 30 and will submit as a pull request. 

The edits I plan to make are:

1. Remove the prerequisite 3 on the lesson that includes "set up git." 
2. Add setting up Git section to Episode 2, "Getting started with Git"
3. Incorporate SSH authentication and set up into Episode 3, "Sharing your work"
4. Update screenshots in Episode 3

**Comment by emcaulay** [comment]
I have forked the lesson and you can see my progress there: [https://github.com/emcaulay/lc-git](https://github.com/emcaulay/lc-git)

**Comment by doingarchives** [comment]
I have reviewed this excellent work. There is a narrow change, and a series of other issues with language, information and pedagogic intent. I think we are on a path to resolving these is a reasonable amount of time (say 20 days) ... and I think we should leave this issue open while that work continues.
