### ISSUE TITLE
Consider image file naming conventions

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-git#107]
As suggested by @doingarchives, consider changing our image filenaming technique. 

Specifically, would using [ISO 5127:2017](https://www.iso.org/standard/59743.html) be more effective for organizing our images that support our lessons. 

I would prefer that if we adopt this standard that we do so across all Carpentries lessons. 

Recommended by @chendaniely for discussion.

**Comment by jt14den** [comment]
@emcaulay for what files? The files we create while teaching the lesson? Or the images and assets we use in the lessons?

**Comment by emcaulay** [comment]
This was a recommendation from @doingarchives on PR #106. in order to separate out new topics, I made this issue from his comments. 

I don't think his recommendation matches how the Carpentries lessons are designed, but as a new maintainer, I am unprepared to do anything other than surface this issue for comment.

**Comment by jt14den** [comment]
Took a look at #101 & I agree with @emcaulay above about doing it carpentries wide. I suggest flagging an issue and starting a conversation on the repo that sources the lesson example: https://carpentries.github.io/lesson-example/. That way any convention adopted has a better chance of persisting across all lessons.

**Comment by emcaulay** [comment]
@jt14den , I don't understand the reference to PR #101, did you mean issue #101?

**Comment by emcaulay** [comment]
I have verified with existing sources (see below) that there are no existing guidelines in the Carpentries for filenaming of image files that serve as illustrations in the lessons. While I and several maintainers agree a filenaming convention would be useful, it's a practice that should be developed across all lessons.

Since I am a new maintainer, I'm most concerned about doing my core responsibilities in maintaining the lessons I have been assigned. The responsibilities are described here: https://docs.carpentries.org/topic_folders/maintainers/maintainers.html#maintainer-guidelines and developing a guideline for the all lessons in the Carpentries is larger than the assigned responsibilities. Therefore, I am not going to take on this new work at this time. 

The recommendation is a good one, but should be referred to a different group. I will look into finding out what group that might be. 

**References**
I have looked for guidance about whether filenaming rules for image files already exists through these methods:
- asked the Carpentries Core Team
- posted on the Carpentries Slack #maintainers channel
- read the Maintainer Guidelines that are part of the Carpentries Handbook

**Comment by zkamvar** [comment]
**I believe this issue can be closed** and can be reviewed in a broader (Carpentries-wide) context at a later time because, on the whole, it is a change that has no obvious improvement for the audience for our lessons (learners/instructors) and is thus not urgent.

**Comment by emcaulay** [comment]
Thank you, @zkamvar. I appreciate your review and I know from your work on the mechanics of how lessons function in github and gh-pages that you are best poised to carry this issue forward to a time when it will be best for wider discussion.
