### ISSUE TITLE
Capitalise 'Git'

### ISSUE THREAD

**Issue by doingarchives** [LibraryCarpentry/lc-git#109]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

Embedded in the capitalisation conventions is the notion of legal status. (The US Constitution defines the roles of an Office of the President ... so we capitalise). 

Here 'GITHUB' (5082896)and 'Git' (4680534 ) [n02] are United States US Trademarks, see < https://bit.ly/3Cm1gVt >. 

For this reason (and the global nature of LC work), the first instance of using this term in the lesson should be made transparent. The authoritative resource that crosses the most disciplines in generally The Chicago Manual of Style CMOS.

CMOS Rule 8.154 tells us that brand names beginning with a capital letter look like 'Git' are unchanged because the 'G' indicates the legal status. Something like iTunes is also OK because the 'T' serves as a indicia of legal status.

The proposed pull requests should make the legal status transparent - not just for US audiences but for WIPO purposes in a lesson at the first textual (not title) instance.

notes
01 \ GitHub, Inc.
02 \ Software Freedom Conservancy, Inc.

**Comment by emcaulay** [comment]
The instructions above are very authoritative and read like they are copied from somewhere. I don't understand the context, but can you please provide a reference to the source. 

Specifically, this sentence: 

> "The proposed pull requests should make the legal status transparent - not just for US audiences but for WIPO purposes in a lesson at the first textual (not title) instance." 

This statement does not sound relevant to The Carpentries audience or the purpose of this lesson. Or even seem relevant to someone writing a scholarly article. I love the _Chicago Manual of Style_ but highlighting the legal status of Git as a trademarked entity is not relevant to our writing here.

**Comment by doingarchives** [comment]
If you have a chance glance at the Chicago Manual of Style rule language. Alternately if you have access to the editorial guide at the publishers of the trade books you described earlier. This is a monetised world - the attributions need to anticipate intellectual property rights.

**Comment by ErinBecker** [comment]
Capitalization of the word "Git" is in line with usage on the [Git homepage](https://git-scm.com/), as well as our usage in the other Carpentries git lesson: https://github.com/swcarpentry/git-novice/issues/505. This issue seems very straightforward to me and not in need of getting into legalese.

**Comment by doingarchives** [comment]
Opinion noted - but we should do a PR to reference Git (TM US 4680534) the first time it is used in the lesson body - thus making transparent that this term belongs to the Software Freedom Conservancy, Inc. (and no one else). They are invested in IP compliance and enforcement work (see their discussion of Copyleft Compliance Projects). As noted at several points - these lesson instructions supplement or relate back to help documents found at < https://git-scm.com >. Respectfully, the transparency of the IP rights is both good risk management practice - and aligns LC with those who built these tools we use in our work. Could we ask the Carpentry General Counsel to consider the practice?
