### ISSUE TITLE
Consider revising the opening to the Episode 2 "Using Git" section

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-git#110]
This section begins with kind of a negative and also arrogant tone, and might be worth revising. 

> One of the main barriers to getting started with Git is the language. Although some of the language used in Git is
fairly self-explanatory, other terms are not so clear. The best way to get to learn the language - which consists of a
number of verbs such as `add`, `commit` and `push` (preceded by the word 'git') - is by using it, which is what we will be doing during this lesson. These commands will be explained as we proceed from setting up a new version-controlled project to publishing our own website.

**Comment by doingarchives** [comment]
Agreed. I've re connected on Slack (under doingarchives) - perhaps we can discuss this further there.

**Comment by michellehudson** [comment]
I made a small attempt at rephrasing, of course feel free to use/change/not use anything! 

One of the main barriers to getting started with Git is understanding the terminology necessary to executing commands. Although some of the language used in Git aligns with common-use words in English, other terms are not so clear. The best way to learn Git terminology - which consists of a number of verbs such as add, commit and push (preceded by the word 'git') - is to use it, which is what we will be doing during this lesson. We will explain these commands as we proceed from setting up a new version-controlled project to publishing our own website.

**Comment by emcaulay** [comment]
This is super -- thank you! I will work on a pull request to incorporate your request soon.

**Comment by doingarchives** [comment]
@michellehudson Nice comment. I agree this language is an enhancement to the lesson. Also thanks @emcaulay for putting forth the effort to make a PR. I'll remove myself from this since it seems well on the way to being fixed appropriately. Let me know if I can be of assistance. Best, Christopher

**Comment by jt14den** [comment]
I jumped in and made the attached PR for this @emcaulay & @michellehudson.
