### ISSUE TITLE
Evaluate purpose of strange pair of sentences

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-git#111]
Mentioned as part of pull request #106 , there are two sentences that don't seem helpful that the reviewer noticed, but reviewer did not note which episode or line. 

The sentences are:

""If you are stuck here, look at the set up instructions for this lesson. The best way to solve the problem is register for a free Git account".

I can't find those sentences in the lesson right now, so I'll have to go back and find them and evaluate what the purpose of those sentences are and if they can be removed or revised.

**Comment by doingarchives** [comment]
@emcaulay Hello. I think this line (or something like it would be useful). I'll add as a pull request next monday.

**Comment by emcaulay** [comment]
I did a search across all episodes in the lesson, and I think after re-reviewing the discussion on #106 that these two sentences were proposed as additions to a section of the lesson. However, the comment is not attached to which part of the revision the reviewer is suggesting be amended. Since we ask the learners to register for a free GitHub account as part of the setup, I don't think this suggestion is necessary.
