### ISSUE TITLE
[Feature request] Add git diff, git log commands to Episode 2

### ISSUE THREAD

**Issue by bkamapantula** [LibraryCarpentry/lc-git#117]
While teaching this lesson, I realized two commands can help the learners onboard to git better:

1. `git diff` - to view unstaged changes
2. `git log` - to view commit history

We can add it to the [Getting Started](https://librarycarpentry.org/lc-git/02-getting-started/index.html) episode.

I'm happy to make the contribution if we're good with the suggestion.

**Comment by emcaulay** [comment]
These are super commands to recommend including in this lesson. I think they are good commands and reasonable for this lesson. I welcome your contribution, @bkamapantula ! Thank you!

**Comment by bkamapantula** [comment]
will do @emcaulay

**Comment by benjwolff** [comment]
In the meantinme `git log` and `git diff` were introduced in [Episode 3](https://librarycarpentry.org/lc-git/03-sharing/index.html). So I think this issue can be closed.

**Comment by emcaulay** [comment]
thank you, @benjwolff !
