### ISSUE TITLE
Scheduling early transition to Workbench

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/lc-git#137]
Short version: **are you are willing to volunteer your lesson for early transition to The Carpentries Workbench 
infrastructure?**

---

Longer version below:

As I hope you are already aware, @zkamvar and the rest of the Curriculum Team are preparing to roll out the new lesson infrastructure, [The Carpentries Workbench](https://carpentries.github.io/workbench/), across all of The Carpentries official lessons in early May 2023. This means that all Data Carpentry, Library Carpentry, and Software Carpentry lesson repositories will be modified to adopt the new infrastructure at the end of this month.

As you might imagine, coordinating a rollout like this involves a large amount of time and effort, and one thing that will really help us to keep to the schedule and avoid disruption for the community is to be able to **prepare some lessons for 
transition before the 1st May deadline**.

With this in mind, **I invite you to volunteer to schedule an early transition for theis lesson repository.** If you expect to have time to adopt the Workbench version of the lesson repository in the next couple of weeks, please reply to let me know. As lesson Maintainers, these are the things you will need to be prepared to do for the transition:
1. **Be prepared to quickly merge pull requests from Zhian**. These pull requests will help update the lesson and aid the transition process.
2. **Close any outstanding pull requests.** Your repository currently has very few or zero open PRs, but we cannot rule out the possibility that someone will open more in the time between now and when the transition takes place. [Open PRs will be invalidated when the transition takes place](https://carpentries.github.io/sandpaper-docs/pull-request.html#transition-from-carpentriesstyles).
3. **Preview the lesson (in the https://github.com/fishtree-attempt organisation) when it is available**. Zhian will open an issue in your repository, tagging you when the preview is available. You should reply on that issue if you notice any problems with the Workbench version of the lesson site and repository in the preview.
4. Just before the transition happens, the repository will be temporarily set as read-only and an issue will be opened (see an example from the Maintainer Onboarding curriculum: https://github.com/carpentries/maintainer-onboarding/issues/69) 
5. After the transition, **delete and recreate any forks and local clones** you have of the repository and then **confirm that you have done so** (you will be given specific instructions in an issue).

If you are willing and able to help us ensure a smooth rollout of the Workbench, please reply to let me know that you are happy to volunteer your lesson for early transition. If there is a specific date you would like the transition to take place (or that we should avoid), please also mention that.

**Comment by tobyhodges** [comment]
I have [reviewed the remaining open PR](https://github.com/LibraryCarpentry/lc-git/pull/126#pullrequestreview-1391501002), and recommend that you go ahead and merge it.

**Comment by emcaulay** [comment]
I have merged it. And I've entered a new one from myself. I'm going to merge it even though generally I prefer to have another reviewer.

**Comment by zkamvar** [comment]
note: the transition of this lesson is tracked in https://github.com/carpentries/lesson-transition/issues/63

**Comment by zkamvar** [comment]
I apologise, I was unable to make the transition happen today. There is nothing impeding the transition itself, it's just a matter of a lot of outside factors coming together in ways that took away my time. The transition process itself takes ~ 5 minutes total, but as you can imagine, it's a very stressful transition on my part because I am changing something that a lot of people have put a lot of time an effort into. Thus, I like to give myself at least two hours for the transition to happen so that I can correct anything if it goes wrong.

I will try again tomorrow. Thank you for your patience.

**Comment by zkamvar** [comment]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @jt14den (admin)
 - [ ] @jezcope (admin)
 - [ ] @ostephens (admin)
 - [ ] @emcaulay (push)
 - [ ] @laufers (push)
 - [ ] @cmacdonell (admin)
 - [ ] @chennesy (push)
 - [ ] @weaverbel (admin)
 - [ ] @annajiat (push)
 - [ ] @drjwbaker (admin)
 - [ ] @r2c0der (push)
 - [ ] @ccronje (admin)
 - [ ] @U2NG (admin)
 - [ ] @pitviper6 (admin)
 - [ ] @PhilReedData (push)
 - [ ] @ragamouf (push)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The deed is done. The infrastructure takes a few minutes to bootstrap and cache the packages for the lesson build. Once the build is done, I will switch github pages to deploy from the `gh-pages` branch and you will have your workbench lesson. 

Thank you all for your enthusiasm and your patience!

**Comment by PhilReedData** [comment]
I am ready for write access :rocket:

**Comment by emcaulay** [comment]
Hi @zkamvar , 
I am ready for write access :rocket:

**Comment by zkamvar** [comment]
@emcaulay access granted!

@r2c0der, are you ready for write access?

**Comment by emcaulay** [comment]
Assigning to @ErinBecker who will close this issue on 2023-11-01.

**Comment by emcaulay** [comment]
@ErinBecker , reminder that I think this issue can now be closed?

**Comment by ErinBecker** [comment]
Hi @r2c0der  - You no longer have Maintainer access to this repository. Please see the comment above for details. If you would like to restore your access, please re-clone the repository on your machine and then comment here with I am ready for write access 🚀 and the admin maintainer of this repository will restore your permissions. If you have any questions, please don’t hesitate to get in touch [curriculum@carpentries.org](mailto:curriculum@carpentries.org)

To the remaining Maintainers for this lesson - the Curriculum Team will be prioritizing onboarding of new Maintainers for lessons that have lost Maintainers in our next round of onboarding. Please don’t hesitate to reach out if your lesson needs additional support in the meantime - [curriculum@carpentries.org](mailto:curriculum@carpentries.org).

I will close this issue now but will still be notified of any replies on the thread in future.
