### ISSUE TITLE
Link to Gitter dicussion forum leads to Page not found

### ISSUE THREAD

**Issue by stephr1000** [LibraryCarpentry/lc-git#149]
In this lesson, https://librarycarpentry.org/lc-git/discuss.html , the first bullet reads "Join our [Gitter discussion forum]" but the URL  (https://gitter.im/LibraryCarpentry/).  goes to a page not found.   I don't know what the correct URL should be.

**Comment by kaitlinnewson** [comment]
Gitter has been deprecated for Library Carpentry, so this link can be removed.
