### ISSUE TITLE
Episode #2: Staging Area yellow section

### ISSUE THREAD

**Issue by deafeningraisins** [LibraryCarpentry/lc-git#19]
So, the phrase "staging area" implies that it's a needed step for this lesson. The information under that section is really a "note" or a "tip". Using either of these terms would be much clearer.

**Comment by jcoliver** [comment]
Possibly addressed by #27 . Note the box was copied from the Software Carpentry lesson, and the title reflects the topic of the contents. Not sure if there are guidelines for how to title boxes ("Tip" is used intermittently, but not consistently).

**Comment by libcce** [comment]
@deafeningraisins created https://github.com/LibraryCarpentry/lc-git/pull/29 as a fix. Does this help?
