### ISSUE TITLE
Git installation issues for Mac for Prerequisites 

### ISSUE THREAD

**Issue by deafeningraisins** [LibraryCarpentry/lc-git#21]
In a number of instances, installing Git onto a Mac computer requires the download of XCode, a free Mac application. The need for that application is not documented and it probably should be. The XCode application is 5GB, which requires a lot of time to download. There's no instruction about how to deal with XCode anywhere. In addition, though it's not a problem associated with Carpentry, the SurgeForce Git application looks a little scary because the package requires a couple of leaps of faith: you have to disable an important security feature on your computer, and you have to believe that the incorrect operating system name (it says it's Maverick and the latest OS is High Sierra) given to the latest version is not going to harm your system.  Please document this somewhere.

**Comment by katrinleinweber** [comment]
Since this is being discussed in https://github.com/carpentries/workshop-template/issues/454 & #42 and the issues linked there. I'm sorry that this issues has not been answered, as but one of the new maintainers, I would like to focus the discussion where it is already happening.
