### ISSUE TITLE
Episode #2 Key Points

### ISSUE THREAD

**Issue by deafeningraisins** [LibraryCarpentry/lc-git#22]
From a beginner's perspective, we've mentioned metadata only once in the text of this lesson. I think the term could be used a lot earlier in this lesson. 

In addition, the second Key Point notes that there is a 2-stage commit process. As a beginner, I'm looking for stages distinctly identified as such in the lesson to verify my understanding. We could clearly identify those stages as distinct by using headers like, "Committing to Changes, Stage 1", etc. in the organization of the page.

**Comment by emcaulay** [comment]
I made some minor revisions to Episode 2 to address the suggestions from @deafeningraisins. Thank you for the ideas, and it's possible we will do more updates to the part about the two-step dance of "add" and "commit" in git. However, hopefully I did signpost the "keypoint" more clearly in the body of the lesson by using a heading of "Two Steps: Adding and Committing"

**Comment by emcaulay** [comment]
I would like to close this issue, but I am not sure I have the authority to do that. To summarize for a maintainer, I believe I have addressed the concerns raised by the issue. However, I welcome discussion if there are more changes desired.

**Comment by emcaulay** [comment]
Fixed by #104.

**Comment by emcaulay** [comment]
Closing this issue since it was fixed by #104. Thank you, @deafeningraisins, for helping us improve this lesson!
