### ISSUE TITLE
Episode #2 opening the file you created

### ISSUE THREAD

**Issue by deafeningraisins** [LibraryCarpentry/lc-git#23]
From a beginner's perspective, once I've created the file on a Mac you cannot easily find it. The file is not where you think it is if you try to browse to it. It's more foolproof to have users use Finder to search for it, then have them open it in a text editor. It would be useful to include XCode as a text editor here, because it becomes the default for SOME Mac users.

**Comment by dcmcand** [comment]
We try to be OS agnostic. Nano is built into the Windows git-cli and almost all linux/bsd distros. XCode is Mac only, so isn't really appropriate to have in an OS agnostic lesson. However, if you think there needs to be more clarification around choosing a text editor or finding files, Please submit a new issue or PR.
Thanks for your comments!
