### ISSUE TITLE
Unlinked Markdown links in the Instructor Guide

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-git#32]
This seems to result from https://github.com/LibraryCarpentry/lc-git/blame/gh-pages/_extras/guide.md#L25-L93. The missing links should be added to https://github.com/LibraryCarpentry/lc-git/blob/gh-pages/_includes/links.md and pushed to #51.

**Comment by dcmcand** [comment]
closed by #51
