### ISSUE TITLE
Prefer official tutorials over Help & Guides?

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-git#34]
[`Reference.md`'s `Further Reading`](https://github.com/LibraryCarpentry/lc-git/blob/gh-pages/reference.md#further-reading) lists some text-only resources.

Since before that GitHub Desktop had an interactive tutorial repo, and recently [GitHub's Learning Labs](https://lab.github.com/) started. Do you have experience with those? Are they useful to be added to our [reference](https://github.com/LibraryCarpentry/lc-git/blob/gh-pages/reference.md#further-reading)?

IMHO, their official character and interactivity make them almost must-haves.

**Comment by libcce** [comment]
I agree, added the resources here https://github.com/LibraryCarpentry/lc-git/pull/35
