### ISSUE TITLE
What to teach

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-git#36]
History of this: https://github.com/data-lessons/library-git-DEPRECATED/issues/58
and this too: https://github.com/data-lessons/library-git-DEPRECATED/issues/7
and this: https://github.com/data-lessons/library-git-DEPRECATED/issues/34
and this: https://github.com/data-lessons/library-git-DEPRECATED/issues/42

**Comment by dcmcand** [comment]
I will be opening an issue looking at updating the structure of the lesson. Closing this one now.
