### ISSUE TITLE
Rewrite gh-pages part, because those can be generated from master

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-git#39]
Because we don't teach the concept of branching elsewhere in the lesson, and because GitHub can generate [pages from `master`](https://help.github.com/articles/user-organization-and-project-pages/#project-pages-sites) as well by now, I think we can simplify the ["gh-pages branch" section in episode 5](https://github.com/LibraryCarpentry/lc-git/blob/gh-pages/_episodes/05-github-pages.md#the-gh-pages-branch).

Maybe by switching simply `gh-pages` to `master`, or by referring completely to the [official tutorial on pages.GitHub.com](https://pages.github.com/)? What do you think?

**Comment by sprklinginfo** [comment]
I am actually thinking about branching after going through the materials a couple of times. 'Branching' is one of the basic concepts in Git and it seems a little strange without explaining it at all, though in "Getting started with git" episode it says, "The output tells us that we are on the master branch (more on this later)...", and this "more on this later" never happens.

**Comment by libcce** [comment]
@sprklinginfo I have taught branching earlier on when I've taught this lesson in line with what you are saying. Having said this, the Maintainers of this lesson are talking about changes we would like to make (based on our own experiences and feedback from others). If you have other thoughts, let us know 😄

**Comment by katrinleinweber** [comment]
Whether or not we teach branching seems like a different issue to me from which branch names to mention ;-)

**Comment by emcaulay** [comment]
Hi all,

Thank you for your discussion here. I wanted to check in and let you know that I have just become a new maintainer for this lesson and I will be reviewing all open issues. I am starting with high priority issues and then working down the list of open issues. I hope to return to this issue in December 2021 or January 2022. 

Thanks,
Lisa

**Comment by doingarchives** [comment]
Probably out of scope. Possibly covered in a re write opportunity that would match a use case with learner contexts in their professional lives. I will close for now.
