### ISSUE TITLE
Use cases to consider/additional context for the lesson

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-git#44]
I'm parking this suggestion from a public library about how we might tailor the training to fit their needs:

For example, you could do the git lesson, but use planning a story time
as the project. That could all be done in plain text, what songs you
sing, what books you read, any rhymes, etc. Then you could show how you
can track changes and share and fork repos etc. That would take these
skills out of the realm of only useful to geeks and help show how all
librarians can benefit.

**Comment by katrinleinweber** [comment]
Was it a single suggestion, or a common theme from a group of learners?

**Comment by libcce** [comment]
@katrinleinweber Single suggestion from a public library.
