### ISSUE TITLE
Reach out to instructors/helpers that have taught Git for their feedback/notes

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-git#45]
Reach out to instructors/helpers that have taught Git for their feedback/notes (scan workshop data https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/master/_data/workshops.yml for Git instructors). Create a new folder in repo called "instructor_notes" where these notes can be submitted to. **Deadline to receive feedback, March 29.**

**Comment by libcce** [comment]
Feedback from instructor: 

- Start from command line and edit files with nano
- It’s clutter free
- Atom/GitHub desktop present too many functions/options which can cause overload
- In the command line we teach each command one by one and write an overview on the white board as a reminder.
- Drawings are important, to demonstrate
   - dots (versions) and lines (commits), to explain the concept of committing changes
   - why "add" and "commit" is used and the staging area (this is done later in the lesson)
   - Most important, used early in lesson, explain ecosystem, how we can work together (draw laptops, push/pull arrows from/to laptops to GitHub/GitLab, also show fork/pull request between them, walk through process, demonstrate how collaboration/software dev has been revolutionized, OER material like Carpentries can be developed, how community can work on shared data like OpenAPCs… we often come back to that drawing when teaching the GitHub part
- not only for source code but also for data, content

**Comment by libcce** [comment]
- post it activity where participants get post its, peeled off of each other to demo that they are copies, with cats drawn on them, participants add something new like a hat or glasses, we then use these post its on the whiteboard to demonstrate forking, making changes, then make a pull request where the changes are accepted and merged or rejected.  This demonstrates this workflow: https://guides.github.com/introduction/flow/. Received positive responses.
- didn't teach command line git - got a sense from the earlier lessons that it would not be useful, wanted learners to be comfortable enough to work with GitHub once they left the classroom. Worked really well. Used extra time to talk about context, how they could use it in library work, and why the workflow is like it is.
- comment at end by participant wishing that more time was spent on GitHub Pages

**Comment by emcaulay** [comment]
These look like a bunch of ideas all listed here as an aggregation. That's excellent and worth taking the time to parse out into distinct issues. 

I have just become a new maintainer on this lesson, and I am addressing high priority issues first. I hope to get back to this issue in November - December 2021.

**Comment by doingarchives** [comment]
Agree with @emcaulay about the need for granularity here. I'm going to close this now ... and float the idea that we look at the pedagogic intent of the class primarily, then connect that with 1-4 examples that reflect the actual audience / use cases for the tool.
