### ISSUE TITLE
Comparison/concept map of GitHub vs Dropbox (or similar)

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-git#47]
Comparison with Dropbox to relate to participants with a tool that they are familiar with.

- [x] https://michaelstepner.com/blog/git-vs-dropbox/
- [x] https://www.dataschool.io/github-is-just-dropbox-for-git/
- [ ] Consider one other tool/scenario as well.

=> [Google Slide](https://docs.google.com/presentation/d/1IwzUhLnhyeIuWQ4fFoXnb13WRuq1Zh_ZPo-V842gwLA/edit)

**Comment by katrinleinweber** [comment]
Shall we use a Google Slide to draw the diagram & include it as an image, or something more formal like [mermaidjs](https://mermaidjs.github.io/mermaid-live-editor/) and commit the source code of the diagram?

**Comment by libcce** [comment]
Slide would probably be the best option. 👍 But @EvaSeidlmayer should probably weigh in.

**Comment by EvaSeidlmayer** [comment]
Hey, the invitation email was lost in the spam folder. However, now I'm in. I'm okay with Google Slide.

**Comment by EvaSeidlmayer** [comment]
One more helpful article that supports our approach: https://www.dataschool.io/github-is-just-dropbox-for-git/

**Comment by EvaSeidlmayer** [comment]
Hey, I set up a document and a first sketch for a comparison of workflow of basic functions in Dropbox and Git. Feel free to comment, change, add etc.
here is the link:
https://docs.google.com/presentation/d/1IwzUhLnhyeIuWQ4fFoXnb13WRuq1Zh_ZPo-V842gwLA/edit?usp=sharing

**Comment by EvaSeidlmayer** [comment]
Hey, sorry, I was temporarily knocked out by a cold. @katrinleinweber may I directly comment and complement on your Git-slides?

**Comment by katrinleinweber** [comment]
Yes, sure. They are also set-up for anonymous editing.

**Comment by EvaSeidlmayer** [comment]
Hey, I made some comments and proposals in your Git präsentation. Hope it was okay to comment on the whole presentation. Hopefully my comments contain some useful suggestions.

**Comment by katrinleinweber** [comment]
The discussion has moved into GDocs mostly. Please feel free to clean this thread up and move the facts into the issue body / 1st post.

**Comment by EvaSeidlmayer** [comment]
Hey, sorry, it's my first day back in office today after being sick for like ten days. Actually, I am not sure how to proceed now.  Maybe we could have a short phone call, @katrinleinweber ?

**Comment by EvaSeidlmayer** [comment]
Hey Katrin, Hey Chris, 
I feel like my proposal rather stopped the discussion on a concept map rather than giving an impulse for it. Sorry for that. Please make another draft that might be a better starting point for working further on.

**Comment by libcce** [comment]
Hi @EvaSeidlmayer I just want to double check, the two concept maps focus on sharing files and collaborating on a file, right? I actually think these are two solid concept maps. What is causing us to pause is the approach, command line vs GitHub/GitLab, and we are still gathering feedback. Can we leave this issue open for the moment? We will definitely come back to this concept map.

**Comment by katrinleinweber** [comment]
@EvaSeidlmayer and me drafted more of a flow-chart than a concept map, but we think it may be useful in case the lesson should receive a section about this comparison, see "Slide" links at the very top & feel free to edit or comment.

**Comment by emcaulay** [comment]
Hi all,

Thank you for your work on this issue. I have just become a new maintainer on this lesson and I will be reviewing this issue as soon as I can. I have some higher priority issues to address first. 

Thanks,
Lisa

**Comment by doingarchives** [comment]
This seems beyond the scope for this course. I don't think it is actionable at this time.
