### ISSUE TITLE
Adding important lessons to current roster

### ISSUE THREAD

**Issue by VickySteeves** [LibraryCarpentry/lc-git#5]
There are a few really key important modules currently missing from this lesson -- perhaps the most important is the `git config`. The current lessons would fail because learners can't make a commit without first telling git who they are. I propose the following 6 lessons:

1. what is git and how its different from github
* should also include how git works -- like what's the staging area, WHY IT MATTERS (people don't get why they can't add then commit)

2. setting git up (git config) -- this needs to happen before getting started with git. can't commit changes when you don't have a name or email associated with the commit

3. making a git repository (currently called 'setting up')
* Git: init, add, commit

4. time traveling with git (going back to a previous commit, going back to the current commit) -- exploring history
* Git: checkout

5. sharing your work (title from existing lesson)
* GitHub: making a repository
* Git: push origin master

6. contributing to other people's work (forking, cloning the new repo in your namespace, making a pull requests)
* GitHub: fork + PRs, permissions
* Git: clone `repo`     

I am working on adding them over at: https://github.com/VickySteeves/lc-git

**Comment by VickySteeves** [comment]
Notes from the call (May 10th, 1:30pm EDT):
+ We might want to consider doing this _in reverse_: starting from GitHub and working to git on the command line
+  GitHub only to start? Not even touching git. Teaches issues, forking/pull requests, markdown, using GitHub pages. 
    + 80% UI stuff, 20% command line a good compromise?
+ Maybe not so much content because time is short! Need more space time-wise.

**Comment by jbkieffer** [comment]
Etherpad on Git topic, including links to examples of GitHub only lessons we discussed, is here: http://pad.software-carpentry.org/lc-git-sprint

**Comment by KristinaRiemer** [comment]
Very rough outline for possibly reversing git material. This uses most of the pre-existing material, just in a different order. 

Start with showing GitHub repository (for a GH-pages website or another library-relevant project) to provide motivating example for using GitHub/git
- [need a really good example repo]
- based on scenario 1 in first lesson (https://librarycarpentry.github.io/lc-git/01-what-is-git/) 
- introduce concept of repository (= storing all files associated with a project)
- show different files, README as description
- can be openly available or private

Either fork that repository or create new GitHub repository
- “remote repository”
- make simple GH-pages website? It would be nice to see changes from commits on a website; would have to explain branches

Make changes and commit them entirely in GitHub interface
- keeping track of all changes with both descriptive message and content = version control
- can see who did it and when
- show collaborative nature with commits from multiple people in example GH repo

Create an issue
- to-do lists
- can link to or close with specific relevant commits

Clone GH repo to machine as local copy
- [motivating reason for this?] 

Make commit and push to remote repo
- others can only see it then

Make a commit with a mistake and then go back to previous commit
- can undo changes
- push commit

Make commit on GitHub and then pull to local to demonstrate pulling?

**Comment by VickySteeves** [comment]
Doing some work on this major rework of the materials here: https://github.com/VickySteeves/lc-git/tree/rework-patch.

**Comment by KristinaRiemer** [comment]
A possible slightly different order for the current sections: 
- Using GitHub
Introduce GH website, show cool motivating examples, create new GH repo, create README and do first commit

- GitHub Issues
Another cool aspect of GH that's useful
- Markdown with GitHub
Why plain text is better, using markdown files, create a new markdown file?
- GitHub Pages
Using GH pages to create website, use new markdown file to actually do this?
- Collaborating on GitHub
How to work with other people (example of repo with many contributors), fork and PR a repo? 
- Setting git up
- Bring your GH repo to your computer
- Syncing local changes to GitHub

The GitHub Pages section would have to be redone to do it entirely on GH.

**Comment by KristinaRiemer** [comment]
@VickySteeves if you want to add me as a collaborator to your fork, I can start implementing this, and fleshing out the objectives and creating outlines for each lesson.

**Comment by VickySteeves** [comment]
Invite sent @KristinaRiemer !

**Comment by KristinaRiemer** [comment]
Okay, see f1a2e7b44 for some of these changes.

**Comment by KristinaRiemer** [comment]
One major thing that's missing is providing motivation for learning git and working with local repositories. Working with collaborators?

**Comment by KristinaRiemer** [comment]
Fleshed out the first two sections for the reversed material (6e1f0f5b0). 

If anyone wants to see the actual website, you'll have to clone Vicky's fork and run jekyll on that local repo.

**Comment by libcce** [comment]
@KristinaRiemer sorry it has taken so long to get back to this, but I think your outline is great, I just added two more episodes, what do you think? Also, what do the maintainers think, @weaverbel @jezcope? If we like it, I'd like to do the rewrite. Looks like @KristinaRiemer @VickySteeves have done some work already 😄 

What is Git/GitHub?
Recognize why version control is useful, distinguish between Git and GitHub

Using GitHub
Introduce GH website, show cool motivating examples, create new GH repo, create README and do first commit

GitHub Issues
Another cool aspect of GH that's useful

Markdown with GitHub
Why plain text is better, using markdown files, create a new markdown file?

GitHub Pages
Using GH pages to create website, use new markdown file to actually do this?

Collaborating on GitHub
How to work with other people (example of repo with many contributors), fork and PR a repo?

Remotes in GitHub
Explain what remote repositories are and why they are useful, push to or pull from a remote repository (can use desktop client or on the command line?)

**Comment by katrinleinweber** [comment]
Hello everyone,

I see two potential PR's here: from [`setup-`](https://github.com/LibraryCarpentry/lc-git/compare/gh-pages...VickySteeves:setup-patch) & [`rework`](https://github.com/LibraryCarpentry/lc-git/compare/gh-pages...VickySteeves:rework-patch)`-patch`. Ready to send them and start a review process?

Kind regards,

Katrin


PS: I tried the "GitHub first approach" and a "diagram" suggested here at TIB's FAIR Data & Software workshop. It's approximately 20min long, see https://doi.org/10.5446/37825#t=34:24,56:02. comments welcome.

**Comment by KristinaRiemer** [comment]
Hi everyone. Sorry for not getting any further with this since the Mozsprint. I, somewhat unexpectedly, got a job offer and need to finish my PhD more quickly than was planned, so I don't think I will currently be able to work on this.

**Comment by libcce** [comment]
No worries @KristinaRiemer !!! I think the pause button was also hit as we are in a transition to new Maintainers for the Git lesson https://docs.google.com/spreadsheets/d/18rNY0LOf8zUzMMilWzh-vmhukL_Ty6hu3_nngkyCmus/edit#gid=0. Currently, the new Maintainers are Thea Atwood, Drew Heles, Katrin Leinweber, Eva Seidlmayer and I. There will be an announcement soon about all of this. @katrinleinweber knows all about this. BTW @katrinleinweber, thanks for sharing the flipped lesson starting with GitHub! Will have to look at it this week!

**Comment by libcce** [comment]
>> In any case: This issue can be closed, right?

Good question @katrinleinweber , I think it is fine to leave it open until the maintainers are onboarded (in the new year). Unless you think we should use another mechanism to gather all the ideas for developing this lesson further?

**Comment by dcmcand** [comment]
Many of these issues have been addressed. I am going to close this now, please open new issues for any remaining issues that need to be addressed.
