### ISSUE TITLE
Check to see if pushing changes section is correct

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-git#59]
I didn't necessarily have the same result in the Sharing your work > Pushing changes section. 
https://librarycarpentry.org/lc-git/03-sharing/index.html

I tried 
git push -u origin master 
and got:

To https://github.com/libcce/hello-world.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/libcce/hello-world.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Do others get the same response?

@katrinleinweber @dheles @tpatwood @EvaSeidlmayer

**Comment by katrinleinweber** [comment]
Does your local commit also have [`4cfd579e59742aa1d9ff41578899ed28636fa88c`](https://github.com/libcce/hello-world/commits/master) as its hash? If not, I guess you rebased or amended the local commit.

**Comment by libcce** [comment]
My hacked approach included:

git checkout master
git remote add upstream 
git fetch upstream
git rebase upstream/master

Which worked at the end of the day.

I'm testing the exercises and got hung up at this point and got error messages.

**Comment by dcmcand** [comment]
Hi @libcce 
This normally occurs when you initialize your remote repo with a README.md, a .gitignore or a LICENSE.txt. The lesson does state "GitHub will ask if you want to add a README.md, license or a .gitignore file. Do not do any of that for now." Any suggestions for how to make that clearer?

**Comment by libcce** [comment]
@dcmcand I recommend closing this issue since the structure of the lesson will be revisited (and this was directed at testing the exercises at the time).
