### ISSUE TITLE
Episode 3 - Pushing Changes section, output has extra prompt and command

### ISSUE THREAD

**Issue by wickr** [LibraryCarpentry/lc-git#61]
https://librarycarpentry.org/lc-git//03-sharing/index.html

The Pushing Changes section shows the output of `git push -u origin master` but also has an extra prompt and a `git status` included:
```
PS C:\github\hello-world> git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```
I think this should be removed from the output block entirely, since `git status` following the push is covered just a couple lines down, and has the same exact output, all formatted correctly.

**Comment by tpatwood** [comment]
Nice catch! The extra language has been removed.
