### ISSUE TITLE
Link "Configure your git setup" returns a 404

### ISSUE THREAD

**Issue by kmhettne** [LibraryCarpentry/lc-git#67]
[Configure your git](https://librarycarpentry.org/setup.html) setup under “Prerequisites” in [this lesson](https://librarycarpentry.org/lc-git/) returns a 404.

<img width="715" alt="Screenshot 2019-06-25 at 20 54 09" src="https://user-images.githubusercontent.com/1397509/60327519-f3b4f900-9983-11e9-8f47-67e21bc522e5.png">

**Comment by libcce** [comment]
Thanks @kmhettne! This PR https://github.com/LibraryCarpentry/lc-git/pull/68 fixes it.
