### ISSUE TITLE
Broken link to "Keeping email address private" 

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-git#72]
On the Git Lesson [Instructors Guide](https://librarycarpentry.org/lc-git/guide/index.html) the link to keeping your email address private is not working.

It is:  https://help.github.com/en/articles/about-commit-email-addresses

Some possible alternatives: 
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/blocking-command-line-pushes-that-expose-your-personal-email-address

**Comment by marswrae** [comment]
This link has not been updated yet and seems important.

**Comment by dcmcand** [comment]
Hi @maneesha,
Thanks for raising this issue. I have merged the pull request fixing this (#76 ) by @marswrae. Thanks for helping to keep this lesson up to date. Sorry for the long wait to get this addressed.
