### ISSUE TITLE
Change order of lesson to teach a Github first approach

### ISSUE THREAD

**Issue by dcmcand** [LibraryCarpentry/lc-git#82]
Many librarians could get benefits from git without ever touching the command line. Teaching github first would show people how to be immediately productive with git and allow them to learn the concepts without the added cognitive load of dealing with the command line.

**Comment by dcmcand** [comment]
Converted this issue to a project that we can organize other related issues under.

[Change lesson structure to teach Github first](https://github.com/LibraryCarpentry/lc-git/projects/1)

**Comment by ErinBecker** [comment]
Not sure where to put this, but this lesson uses a GH focus: https://dlstrong.github.io/git-novice/
