### ISSUE TITLE
move lesson to stable

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-git#84]
This lesson is listed as *core*, but is still listed as `beta`. What still remains to move this lesson to `stable` and then publish?

**Comment by dcmcand** [comment]
Hi @jt14den,
Perhaps @libcce can provide more context for this. He and I have been discussing how to provide library specific use cases to this lesson to justify having a seperate lesson for SWC, and the possibility of changing to a github first approach to this lesson to make it less of a jump into the deep end at the start of the lesson. I am brand new to maintaining this lesson though, so hopefully @libcce  or others can chime in here.

**Comment by jt14den** [comment]
@dcmcand cool! Thanks. At one of the previous sprints there was some thought put into flipping the lesson (github first), but it didn't happen. @libcce will know more about that. I brought this up now b/c there are some upcoming LC workshops and I was asked if the lesson is ready to be taught because it is `beta` or if the instructor should use SWC git instead.

**Comment by libcce** [comment]
@jt14den the lesson is stable from the original structure that James provided. The GitHub first approach still lives in a lesson sprint Google doc which I've shared with @dcmcand so he has background. Also lives in some Etherpads, also shared. The way the lesson is now, in beta, is the same lesson @jt14den we taught at UCLA when I first started w/ LC. So if you want to stick to the structure as it is now? The flipped approach @pitviper6 and I have tried has been pretty successful from what I've seen from the feedback. But yes, as mentioned in the LC Advisory Group, getting LC Git to stable is a priority along with Tidy Data.

**Comment by libcce** [comment]
Oh and you are doing a great job @dcmcand! I'm so thankful that you are cleaning up issues/PRs and then looking at the overall structure. We need this 😄

**Comment by dcmcand** [comment]
Thanks @libcce!

@jt14den I agree that the lesson is stable for its current structure and wouldn't have a problem with it being marked as such. I have taught it a couple of times in its current form and it worked just fine. The only thing is that it really does need the Unix shell taught prior to it or you spend half of your time just talking about the shell commands that are used in this lesson. 

We could call this v1.0.0 and save v2.0.0 for the flipped structure if we wanted to get into semantic versioning
