### ISSUE TITLE
Git Repositories

### ISSUE THREAD

**Issue by bkmgit** [LibraryCarpentry/lc-git#96]
It may be helpful to add information about GitLab, Bitbucket, Sourceforge, Gitea, Gitee and other similar git collaboration software, since many people may need to use these and the workflow is similar.

**Comment by dcmcand** [comment]
Hi @bkmgit 
Do you have any suggestions for language? I would welcome a pull request with your suggestions to review.
Regards
Chuck

**Comment by bkmgit** [comment]
Made a pull request. Am happy to revise and/or extend.

**Comment by dcmcand** [comment]
Closed by #97
