### ISSUE TITLE
Change master to main in episode 3

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-git#99]
The GitHub default branch is now `main` not `master`. However, creating a git repository locally will be by default  in a `master` branch. This creates a problem when we connect the local and remote branch in "Sharing Your Work", Episode 3: https://librarycarpentry.org/lc-git/03-sharing/index.html. 

Solution: adopt what GitHub suggests after you create a repository there. This means changing the image in Sharing Your Work from starting with  "…or push an existing repository from the command line" under **Connecting your local repository to the GitHub repository**  to the new instructions: 

```
git remote add origin https://github.com/some-librarian/hello-world.git
git branch -M main
git push -u origin main
```
Possibly include the text of the code rather than the image so it's more copy and pasteable. We also need to then change all references from `master` to `main` in the lesson.  @scottcpeterson and I are teaching this on 1/29 and can come back with a PR.

**Comment by emcaulay** [comment]
Thank you @jt14den, @burrowsdt, and @srappel for your work on this. I see that some of the screenshots (or at least one of them) will need updating, too. 

The one I noted is: https://github.com/LibraryCarpentry/lc-git/blob/gh-pages/fig/github-instructions.png. 

I will leave this issue open until I complete that update. 

I am a new maintainer and just getting started so please be patient as I get going.

**Comment by doingarchives** [comment]
Agreed. These graphics should be named sequentially and stored in a file appended to the course. We should reference this somewhere < https://bit.ly/2VtZ5OX >. If we consistently adopt the bitly links - in a period of time (months) we'll have some alt metrics to help guide future maintenance tasks.

**Comment by emcaulay** [comment]
I just took a review of this topic relative to the LC lesson on Git (this lesson). I think we also need changes to Episode 2. 

When I used the command `git init` on my local machine, the default branch was named `master.` So I would need to define the default branch as `main` on my machine. 

@jt14den do you think I need to update my global git settings? @ErinBecker, can you also help me review this lesson to make sure we are providing instructions that work for new Git users?

**Comment by jt14den** [comment]
@emcaulay I still haven't set mine, but recall seeing git suggest that at some point when I taught git last week. If we can do that at the beginning of the lesson when we set global configs, I think that would be good. That said, we'd need to test with GH's instructions after creating a repo on GitHub.

**Comment by srappel** [comment]
The lc-git workshop seems to have undergone some major changes since my pull request including moving much of the setup off the setup page and into episode 2. But at the very end of the "[Setting Up Git](https://librarycarpentry.org/lc-git/02-getting-started/index.html#setting-up-git)" section of episode 2, the command `git config --global init.defaultBranch main` should set up git globally to initialize new repositories with the default branch name as _main_.

**Comment by emcaulay** [comment]
I think this work has been fully completed. 

@srappel, thank you for your query, and we do allow there to be some differences between the Library Carpentry lesson and the Software Carpentry lesson.
